### ISSUE TITLE
Some questions about the PositionalEncoding.

### ISSUE THREAD

**Issue by Liqq1** [yangyan22/Medical-Image-Report-Generation-with-CNN-Transformer#1]
Hi! Thanks for your refactoring of the code, which makes it a little easier for me to understand. 
But I have two questions to confirm: 
1. In `encoder_decoder.py/calss EncoderDecoder/def make_model`：
```
model = Transformer(
    Encoder(EncoderLayer(self.d_model, c(attn), c(ff), self.dropout), self.num_layers),  
    Decoder(DecoderLayer(self.d_model, c(attn), c(attn), c(ff), self.dropout), self.num_layers),
    lambda x: x,   
    nn.Sequential(Embeddings(self.d_model, tgt_vocab), c(position)))
```
why was `PositionalEncoding  in encoder` replaced by `lambda x: x`? 

2. Based on R2Gen, are there any methodological changes in the inference stage besides refactoring the code?

Thank you in advance, i am looking forward to hearing from u!

**Comment by yangyan22** [comment]
Hi!
1. I think it's no need to add the position for the visual encoding features, CNN may contain the position information when encoding the medical images which is different from the machine translation task.
2. For the inference, there is no change.

**Comment by Liqq1** [comment]
get it, thanks a lot!
