### ISSUE TITLE
有一些文件没有上传吧

### ISSUE THREAD

**Issue by deng1604** [yangyan22/Medical-Image-Report-Generation-with-CNN-Transformer#2]
作者你好，像论文中提到的MeSH，TF-IDF，三分支网络(TriNet)，新定义的损失函数，好像代码中没有提到呀

**Comment by yangyan22** [comment]
This is a CNN-Transformer-based baseline model, not the TriNet based on HRNN.  Please refer to the https://github.com/yangyan22/Medical-Report-Generation-TriNet.

**Comment by yangyan22** [comment]
Hello, this is a CNN-Transformer-based baseline model, not the TriNet based on HRNN. For TriNet, please refer to the https://github.com/yangyan22/Medical-Report-Generation-TriNet.

**Comment by deng1604** [comment]
> Hello, this is a CNN-Transformer-based baseline model, not the TriNet based on HRNN. For TriNet, please refer to the https://github.com/yangyan22/Medical-Report-Generation-TriNet.

ok, thank you.
